### ISSUE TITLE
defid.exe not found windows, defichain wallet 4.0.7

### ISSUE THREAD

**Issue by KouLiTo** [BirthdayResearch/defichain-app#1290]
[2023-12-10 21:06:33.302] [IPC-MAIN-info]  [Starting Electron App] OS Windows 10 - 10.0.19045
[2023-12-10 21:06:33.308] [IPC-MAIN-info]  Checking for update
[2023-12-10 21:06:35.081] [IPC-RENDERER-info]   "[Starting App] App is running with version 4.0.7"
[2023-12-10 21:06:35.088] [IPC-MAIN-info]  [start] - Starting node connection...
[2023-12-10 21:06:35.090] [IPC-MAIN-info]  Current Node: 4.0.5 New Node: 4.0.5
[2023-12-10 21:06:35.091] [IPC-MAIN-error] Error: C:\Users\Gena\AppData\Local\Programs\DeFi Wallet\resources\bin\win\defid.exe file not available
    at Function.<anonymous> (C:\Users\Amdin\AppData\Local\Programs\DeFi Wallet\resources\app.asar\electron-app\build\electron-app\src\services\defiprocessmanager.js:201:35)
    at step (C:\Users\Admin\AppData\Local\Programs\DeFi Wallet\resources\app.asar\electron-app\build\electron-app\src\services\defiprocessmanager.js:56:23)
    at Object.next (C:\Users\Admin\AppData\Local\Programs\DeFi Wallet\resources\app.asar\electron-app\build\electron-app\src\services\defiprocessmanager.js:37:53)
    at C:\Users\Admin\AppData\Local\Programs\DeFi Wallet\resources\app.asar\electron-app\build\electron-app\src\services\defiprocessmanager.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Admin\AppData\Local\Programs\DeFi Wallet\resources\app.asar\electron-app\build\electron-app\src\services\defiprocessmanager.js:27:12)
    at DefiProcessManager.start (C:\Users\Admin\AppData\Local\Programs\DeFi Wallet\resources\app.asar\electron-app\build\electron-app\src\services\defiprocessmanager.js:115:16)
    at C:\Users\Gena\AppData\Local\Programs\DeFi Wallet\resources\app.asar\electron-app\build\electron-app\src\ipc-events\defiprocessmanager.js:50:78
    at step (C:\Users\Gena\AppData\Local\Programs\DeFi Wallet\resources\app.asar\electron-app\build\electron-app\src\ipc-events\defiprocessmanager.js:33:23)
    at Object.next (C:\Users\Gena\AppData\Local\Programs\DeFi Wallet\resources\app.asar\electron-app\build\electron-app\src\ipc-events\defiprocessmanager.js:14:53)
[2023-12-10 21:06:35.093] [IPC-RENDERER-info]  [setLockTimeout] "Starting update of lock timeout..."
[2023-12-10 21:06:35.096] [IPC-RENDERER-info]  [Auto-Lock-Zeit aktualisieren] "Timeout aktualisiert auf 300 Sekunden"
[2023-12-10 21:06:35.104] [IPC-RENDERER-error] [startNode] "C:\\Users\\Gena\\AppData\\Local\\Programs\\DeFi Wallet\\resources\\bin\\win\\defid.exe file not available"
[2023-12-10 21:06:35.104] [IPC-RENDERER-info]  [Blockchain Status] {"success":false,"data":{}}
[2023-12-10 21:06:35.105] [IPC-RENDERER-error] [blockChainNotStarted - Not Running] ""
[2023-12-10 21:06:35.876] [IPC-RENDERER-info]  Update for version 4.0.7 is not available (latest version: 4.0.7, downgrade is disallowed).
[2023-12-10 21:06:35.878] [IPC-RENDERER-debug] checkForUpdatesAndNotify called, downloadPromise is null

**Comment by beoschmann** [comment]
I have the same issue on Windows 10 Pro, 22H2.

**Comment by KouLiTo** [comment]
I found out that the version 4.0.7 is not really updated by nodes. But you can also go to the directory of ain and find the exe file. You can put it into win folder

**Comment by fullstackninja864** [comment]
The issue has been resolved in the latest version of the DeFiChain wallet, v4.0.8. We'll go ahead and close this ticket accordingly. If you encounter any further issues or have additional concerns, please do create new ticket for that. Thank you for your patience and cooperation!
